-include_lib("feed_server/include/records.hrl").

-define(ROOT, code:priv_dir(web)).

-define(CSS,                "/static/css/igratch.css").
-define(LESS,               "/static/igratch/igratch.less").
-define(REVIEWS_CSS,        "/static/css/reviews.css").
-define(REVIEWS_LESS,       "/static/igratch/reviews.less").
-define(BOOTSTRAP,          "/static/js/bootstrap.min.js").
-define(REVIEWS_BOOTSTRAP,  "/static/js/reviews-bs.min.js").
-define(INDEX_CSS,          "/static/css/index.css").
-define(INDEX_LESS,         "/static/igratch/index.less").
-define(INDEX_BOOTSTRAP,    "/static/js/index-bs.min.js").
-define(LOGIN_BOOTSTRAP,    "/static/js/login-bs.min.js").
-define(LOGIN_CSS,          "/static/css/igratch.css").
-define(PRODUCT_CSS,        "/static/css/igratch.css").
-define(PRODUCT_BOOTSTRAP,  "/static/js/bootstrap.min.js").
-define(MYREVIEW_CSS,       "/static/css/igratch.css").
-define(MYREVIEW_BOOTSTRAP, "/static/js/bootstrap.min.js").
-define(DIRECT_CSS,         "/static/css/igratch.css").
-define(DIRECT_BOOTSTRAP,   "/static/js/bootstrap.min.js").
-define(ADMIN_CSS,          "/static/css/igratch.css").
-define(ADMIN_BOOTSTRAP,    "/static/js/admin-bs.min.js").
-define(PROFILE_CSS,        "/static/css/igratch.css").
-define(PROFILE_BOOTSTRAP,  "/static/js/bootstrap.min.js").
-define(CART_CSS,           "/static/css/igratch.css").
-define(CART_BOOTSTRAP,     "/static/js/cart-bs.min.js").
-define(CHECKOUT_CSS,       "/static/css/igratch.css").
-define(CHECKOUT_BOOTSTRAP, "/static/js/bootstrap.min.js").
-define(STORE_CSS,          "/static/css/igratch.css").
-define(STORE_BOOTSTRAP,    "/static/js/bootstrap.min.js").
-define(MYGAMES_CSS,        "/static/css/igratch.css").
-define(MYGAMES_BOOTSTRAP,  "/static/js/bootstrap.min.js").
-define(REVIEW_CSS,         "/static/css/igratch.css").
-define(REVIEW_BOOTSTRAP,   "/static/js/bootstrap.min.js").

-define(PAGE_SIZE, 4).
-define(BTN_INFO,       [btn, "btn-info"]).
-define(BTN_SUCCESS,    [btn, "btn-success"]).
-define(STACK_BASE,     ["icon-stack-base", "icon-circle"]).
-define(TOOLTIP,        [{<<"data-toggle">>,<<"tooltip">>}]).
-define(DATA_TAB,       [{<<"data-toggle">>,<<"tab">>}]).
-define(DATA_COLLAPSE,  [{<<"data-toggle">>, <<"collapse">>}, {<<"data-target">>, <<".nav-collapse">>}]).
-define(URL_PRODUCT(Id),"/product?id="++wf:to_list(Id)).
-define(URL_REVIEW(Id), "/review?id="++wf:to_list(Id)).
-define(URL_PROFILE(Id),"/profile?id="++wf:to_list(Id)).

-record(struct,         {lst=[]}).
-record(product_hero,   {?ELEMENT_BASE(product), product}).

-define(USR_CART(Id),   wf:to_list(erlang:phash2(Id))++"cart").
-define(USR_ORDER(Id),  wf:to_list(erlang:phash2(Id))++"order").
-define(FD_CHKOUT(Id),  wf:to_list(Id)++"chk").
